name: ASF-docker-ci

on: [push, pull_request]

env:
  PLATFORMS: linux/amd64,linux/arm,linux/arm64

jobs:
  main:
    strategy:
      fail-fast: false
      matrix:
        file: [Dockerfile, Dockerfile.Service]
        os: [macos-latest, ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build Docker image on ${{ matrix.os }} from ${{ matrix.file }}
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ${{ matrix.file }}
        platforms: ${{ env.PLATFORMS }}
        build-args: STEAM_TOKEN_DUMPER_TOKEN=${{ secrets.STEAM_TOKEN_DUMPER_TOKEN }}
